[workspace]
members = [
    "crates/bevy_gltf_components",
    "crates/bevy_gltf_blueprints",
    "examples/bevy_gltf_components/basic/",
    "examples/bevy_gltf_blueprints/basic/",
    "examples/bevy_gltf_blueprints/basic_xpbd_physics/",
    "examples/bevy_gltf_blueprints/animation/"

]
resolver = "2"

[profile.dev]
opt-level = 1 # Use slightly better optimization, so examples work