[workspace]
members = [
    "crates/bevy_gltf_components",
    "crates/bevy_gltf_blueprints",
    #"examples/*"
]
resolver = "2"

[profile.dev]
opt-level = 1 # Use slightly better optimization, so examples work