[package]
name = "bevy_gltf_components"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dev-dependencies]
bevy="0.11.2"

[dependencies]
bevy = { version = "0.11.2", default-features = false, features = ["bevy_asset", "bevy_scene", "bevy_gltf"] }
serde = "*"
ron="*"
