[package]
name = "bevy_gltf_blueprints"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dev-dependencies]
bevy="0.11.2"

[dependencies]
bevy_gltf_components = { path = "../bevy_gltf_components" }
bevy = { version = "0.11.2", default-features = false, features = ["bevy_asset", "bevy_scene", "bevy_gltf"] }